id:
  type: string
  attributes:
    - id
    - hotel_id
    - Id
destination_id:
  type: number
  attributes:
    - destination_id
    - destination
    - DestinationId
name:
  type: string
  attributes:
    - name
    - hotel_name
    - Name
lat:
  type: number
  attributes:
    - lat
    - latitude
    - Latitude
lng:
  type: number
  attributes:
    - lng
    - Longitude
address:
  type: string
  attributes:
    - address
    -
      - location
      - address
    - Address
city:
  type: string
  attributes:
    - City
country:
  type: string
  attributes:
    - Country
    -
      - location
      - country
postal_code:
  type: string
  attributes:
    - PostalCode
description:
  type: string
  mergeable: true
  attributes:
    - details
    - info
    - Description
amenities:
  type: array
  mergeable: true
  attributes:
    - amenities
    - Facilities
    -
      - amenities
      - general
    -
      - amenities
      - room
url:
  attributes:
    - url
    - link
caption:
  attributes:
    - caption
    - description
booking_conditions:
  type: array
  mergeable: true
  attributes:
    - booking_conditions
images:
  type: array
  mergeable: true
  attributes:
    -
      - images
      - rooms
    -
      - images
      - amenities
    -
      - images
      - site
